CSID-DGU/2024-2-SCS4031-jjambbong-3

server/src/main/java/com/capstone/server/controller/UserController.java
server/src/main/java/com/capstone/server/domain/User.java
server/src/main/java/com/capstone/server/dto/UserDto.java
server/src/main/java/com/capstone/server/service/CustomOAuth2UserService.java
server/src/main/resources/application.properties

37 feat be login

---

frontend/src/components/Calendar.module.css
frontend/src/pages/KakaoLoginPage.js
frontend/src/pages/NewChat.js
frontend/src/pages/NewChat.module.css
frontend/src/pages/TestPage.js

#43 
백앤드 통신을 위한 로직 구현
test 환경설정
axios 이용한 통신 구현
test: axios 통신 
어떤 변경 사항이 있나요?

test: 프,백 통신 테스트

---

frontend/src/components/Calendar.module.css
frontend/src/pages/KakaoLoginPage.js
frontend/src/pages/NewChat.js
frontend/src/pages/NewChat.module.css
frontend/src/pages/TestPage.js

43 test fe axios 백엔드 통신 테스트

---

frontend/src/pages/NewChat.js
frontend/src/pages/NewChat.module.css

feat: [FE] API 연결 로직 추가

---

frontend/src/pages/NewChat.js

refactor: [FE] 프론트 충돌 해결

---

frontend/src/pages/NewChat.js
frontend/src/pages/NewChat.module.css
server/build.gradle
server/src/main/java/com/capstone/server/config/SecurityConfig.java
server/src/main/java/com/capstone/server/controller/UserController.java
server/src/main/resources/application.properties

#49 
- API 연결 로직 구현
- 초기 트리거 구현
- 실시간 채팅 연결
어떤 변경 사항이 있나요?

feat: [FE] GPT API 연결 로직 구현

---

frontend/src/App.js
frontend/src/pages/NewChat.module.css

fix: [FE] merge 오류 수정

---

frontend/src/pages/KakaoLoginPage.js
frontend/src/pages/RedirectPage.js

feat: [FE] 카카오 로그인 연결

---

frontend/src/components/DetailedSchedule.js
frontend/src/components/TamtamPlacePreview.js
frontend/src/components/TravelSpot.js
frontend/src/components/TravelSummary.js
frontend/src/components/TravelSummary.module.css
frontend/src/pages/DetailedItineraryPage.js
frontend/src/pages/NewChat.js

#71 
- 여행 계획 생성 시 왼쪽 사이드바 장소 미리보기에서 실시간으로 장소 렌더링됨
- 수정 시에도 수정된 장소 반영
- 여행 상세 일정 페이지에서도 확인 가능
어떤 변경 사항이 있나요?

feat: [FE] 여행 계획 생성 및 수정 시 장소 실시간 렌더링

---

frontend/src/components/TamtamPlacePreview.js
frontend/src/components/TravelSummary.js
frontend/src/pages/NewChat.js

- 일정에 대한 해시태그 추가
- 상세 일정 페이지에서 요약 정보 확인 가능
어떤 변경 사항이 있나요?

feat: [FE] 일정 해시 태그 추가

---

frontend/src/components/InputModal.js
frontend/src/pages/DetailedItineraryPage.js
frontend/src/pages/MyPage.js

- 제목 입력 모달 구현
- 일정 확정 버튼 클릭 후 제목 입력 모달 띄워짐
- 코드 리팩토링 (오류 수정)
어떤 변경 사항이 있나요?

feat: [FE] 제목 입력 기능 추가 및 코드 리팩토링

---

frontend/src/pages/RedirectPage.js

fix: 병합 오류 수정

---

frontend/src/components/DetailedSchedule.module.css
frontend/src/components/TamtamPlacePreview.js
frontend/src/components/TravelSummary.js
frontend/src/components/TravelSummary.module.css
frontend/src/pages/KakaoLoginPage.js
frontend/src/pages/NewChat.js
frontend/src/pages/NewChat.module.css
frontend/src/pages/RedirectPage.js

- 해시태그 로직 수정
- CSS 수정 (상세 일정 페이지 탭 부분)
어떤 변경 사항이 있나요?

feat: [FE] 해시태그 로직 수정 및 CSS 수정

---

frontend/src/components/Calendar.js
frontend/src/components/DetailedSchedule.module.css
frontend/src/components/Sidebar.js
frontend/src/components/Sidebar.module.css
frontend/src/components/Thema.js
frontend/src/components/WithWhom.js
frontend/src/pages/NewChat.js

feat: [FE] 초기 인풋 및 채팅 입력 방지 기능 추가

---

server/src/main/java/com/capstone/server/config/SecurityConfig.java

[BE] feat : user cors오류 수정

---

server/src/main/java/com/capstone/server/config/SecurityConfig.java

[BE] feat : user cors 오류 수정

---

server/src/main/java/com/capstone/server/config/SecurityConfig.java
server/src/main/java/com/capstone/server/controller/UserController.java

- 3000에서는 될듯
- 프론트 배포주소에서는 cors 오류 나는 것 같음
어떤 변경 사항이 있나요?

[BE] fix: user cors 오류 수정

---

server/src/main/java/com/capstone/server/config/SecurityConfig.java
server/src/main/java/com/capstone/server/controller/UserController.java

[BE] feat : user api 제거

---

frontend/src/api/apiClient.js

refactor: [FE] 로그인 API 설정

---

frontend/src/api/userApi.js

refactor: [FE] API 경로 수정

---

frontend/src/components/TravelSummary.js
frontend/src/pages/DetailedItineraryPage.js
frontend/src/pages/Main.js
frontend/src/pages/MyPage.js
frontend/src/pages/NewChat.js

feat: [FE] 사용자 정보 연결

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/KakaoMap.js
frontend/src/components/Route.js
frontend/src/pages/Main.js
frontend/src/pages/Main.module.css
frontend/yarn.lock

회원가입 
카카오맵, 길찾기 정보반영
어떤 변경 사항이 있나요?

merge: [FE] 회원가입 반영 

---

frontend/src/components/DetailedSchedule.js

feat: [FE] 저장한 일정 상세 조회 기능 구현

---

frontend/src/components/DetailedSchedule.js

fix: [FE] 상세 일정 렌더링 오류 해결

---

frontend/src/components/TravelSummary.js

fix: [FE] 여행 요약 렌더링 오류 해결

---

frontend/src/pages/NewChat.js

feat: [FE] 채팅에 마크다운 적용

---

frontend/src/pages/DetailedItineraryPage.js

feat: [FE] 저장된 일정에서 버튼 숨김

---

frontend/package-lock.json
frontend/src/pages/NewChat.js
frontend/src/pages/NewChat.module.css
frontend/yarn.lock

css: [FE] 채팅 버블 css 수정

---

README.md

Update 리드미 살짝

---

frontend/src/pages/NewChat.module.css

css: 채팅 인풋 CSS 수정
